In [1]:
import pandas as pd
import numpy as np # 숫자, 통계와 관련된 라이브러리

In [2]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
dates = pd.date_range('2013-01-03', periods=6)


In [4]:
dates

DatetimeIndex(['2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06',
               '2013-01-07', '2013-01-08'],
              dtype='datetime64[ns]', freq='D')

In [5]:
np.random.randn(1,2) # 랜덤함수 생성

array([[ 0.41769252, -0.72825099]])

In [6]:
np.random.randn(6,2)

array([[ 0.18502344, -0.31749989],
       [ 0.741333  , -0.55954678],
       [-0.28998617,  2.5219076 ],
       [ 0.8118334 , -0.39124922],
       [-1.58004012,  1.4263394 ],
       [-0.3943211 ,  0.91038286]])

In [8]:
np.random.randn(6,4)

array([[ 0.86064871, -2.05970049, -0.25094905,  0.73714301],
       [ 0.35554661,  0.32970972,  0.62888608, -0.48956289],
       [ 0.65480323, -0.49700559, -0.22976549, -0.36748758],
       [-1.09472425, -0.33747971, -0.41261816,  0.62148505],
       [ 0.7093315 , -0.73869747, -0.64838165,  0.72312256],
       [ 1.64719983, -1.35698184,  0.7716794 , -0.45147051]])

In [12]:
df = pd.DataFrame(np.random.randn(6,4),index = dates, columns = ['A','B','C','D'])

In [13]:
df.head(3)

A         B         C         D
2013-01-03 -0.882761  0.348497 -0.437127  0.010710
2013-01-04  1.986114 -0.333596  0.054910  0.046449
2013-01-05 -1.104754  0.767498  0.266362 -1.881062

In [14]:
df.tail(3)

A         B         C         D
2013-01-06  0.218028  0.856598 -1.547839  0.129291
2013-01-07 -1.089628  0.485743 -0.497599  0.915230
2013-01-08  1.405815  0.792752  0.679494  0.560498

In [15]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2013-01-03 to 2013-01-08
Freq: D
Data columns (total 4 columns):
A    6 non-null float64
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [21]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.088802  0.486249 -0.246967 -0.036481
std    1.349683  0.447510  0.775140  0.969660
min   -1.104754 -0.333596 -1.547839 -1.881062
25%   -1.037911  0.382809 -0.482481  0.019645
50%   -0.332366  0.626621 -0.191109  0.087870
75%    1.108869  0.786438  0.213499  0.452696
max    1.986114  0.856598  0.679494  0.915230

In [24]:
df.sort_values(by='B',ascending=False)

A         B         C         D
2013-01-06  0.218028  0.856598 -1.547839  0.129291
2013-01-08  1.405815  0.792752  0.679494  0.560498
2013-01-05 -1.104754  0.767498  0.266362 -1.881062
2013-01-07 -1.089628  0.485743 -0.497599  0.915230
2013-01-03 -0.882761  0.348497 -0.437127  0.010710
2013-01-04  1.986114 -0.333596  0.054910  0.046449

In [25]:
df['A']

2013-01-03   -0.882761
2013-01-04    1.986114
2013-01-05   -1.104754
2013-01-06    0.218028
2013-01-07   -1.089628
2013-01-08    1.405815
Freq: D, Name: A, dtype: float64

In [26]:
df[0:3]

A         B         C         D
2013-01-03 -0.882761  0.348497 -0.437127  0.010710
2013-01-04  1.986114 -0.333596  0.054910  0.046449
2013-01-05 -1.104754  0.767498  0.266362 -1.881062